spring.application.name=transaction-service
server.port=8082

#DB
#spring.datasource.url= url
#spring.datasource.username= username
#spring.datasource.password= password
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

#Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect